version: '3.8'
name: cimb
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: user
      MYSQL_USER: huynh
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"